name: Checkout Sample
on: [push]
jobs:
  checkout-repo-before-and-after:
    runs-on: ubuntu-latest
    steps:
      - name: List files Before checkout
        run: ls -al
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout master

      - name: List files After checkout
        run: ls -al
