name: Checkout
on: [push]
jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files Before checkout
        run: ls -al

      - uses: actions/checkout@v3

      - name: List files After checkout
        run: ls -al
