name: Working directory & Shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory & list files
        run : |
          pwd
          ls -al
          echo "$GITHUB_SHA"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_WORKSPACE"

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display working directory & list files
        shell: bash
        run : |
          pwd
          ls -al
          echo "$GITHUB_SHA"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_WORKSPACE"

  display-wd-info-windows2:
    runs-on: windows-latest
    steps:
      - name: Display working directory & list files
        shell: pwsh
        run : |
          Get-location
          dir
          echo "$env:GITHUB_SHA"
          echo "$env:GITHUB_REPOSITORY"
          echo "$env:GITHUB_WORKSPACE"
      - name: Run Python Shell
        run: import platform
