name: Workflow Test
on: [push]

jobs: 
  run-shell-commads:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v