name: Workflow-commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up error
        run: echo "::error::Missing Semocolon in line no2"
      - name: Setting up error with params
        run: echo "::error tile:not required Semocolon in line no2::Missing colon"