name: Simple Action
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Simple action
              id: greet
              uses: ./.github/actions/docker
              with:
                who_to_greet: Sreenath
            - name: Log Greeting time
              run: echo "${{ steps.greet.outputs.time }}"
            - name: Log ENV Var
              run: echo $HELLO_TIME